### ISSUE TITLE
Can't download from JCenter

### ISSUE THREAD

**Issue by aunthtoo** [vincent-paing/myanmar-phonenumber-kt#4]
Hello bro <br>
Gradle can't download latest version from Jcenter<br>
Maybe cus of JCenter Shutdown?

`> Could not resolve com.aungkyawpaing.mmphonenumber:mmphonenumber:1.1.1.
          > Could not get resource 'https://dl.bintray.com/vincent-paing/maven/com/aungkyawpaing/mmphonenumber/mmphonenumber/1.1.1/mmphonenumber-1.1.1.pom'.
             > Could not HEAD 'https://dl.bintray.com/vincent-paing/maven/com/aungkyawpaing/mmphonenumber/mmphonenumber/1.1.1/mmphonenumber-1.1.1.pom'. Received status code 502 from server: Bad Gateway`

**Comment by vincent-paing** [comment]
Yes, I will move to Maven Central by this weekend, was busy with moving stuff, and forgot about this. You can build a jar from source until then

**Comment by vincent-paing** [comment]
Use [1.1.1](https://github.com/vincent-paing/myanmar-phonenumber-kt/releases/tag/v1.1.1) release for maven central.
